# -*- coding: utf-8 -*-
"""Ultralytics Object detection .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yjlk0_W_yXpJaMeARafVTR7OJnBuxc16
"""

pip install ultralytics

!pip install torch

from ultralytics import YOLO
import torch

# Load the pre-trained YOLOv8 model
model = YOLO('yolov8n-seg.pt')

results = model(source="licensed-image.jpeg", show=True, conf=0.4, save=True)

# prompt: generate every possible output for this segmentation model

# Generate all possible outputs for the segmentation model
outputs = model(source="licensed-image.jpeg", agnostic_nms=False)

# Iterate through the outputs
for output in outputs:
    # Extract bounding boxes, classes, names, and confidences
    boxes = output.boxes.xyxy.tolist()
    classes = output.boxes.cls.tolist()
    names = output.names
    confidences = output.boxes.conf.tolist()

    # Print the information for each bounding box
    for box, cls, conf in zip(boxes, classes, confidences):
        print(f"Bounding box: {box}")
        print(f"Class: {names[cls]}")
        print(f"Confidence: {conf}")