# -*- coding: utf-8 -*-
"""Ultralytics Object detection .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yjlk0_W_yXpJaMeARafVTR7OJnBuxc16
"""

pip install ultralytics

from ultralytics import YOLO

# Load the pre-trained YOLOv8 model
model = YOLO('yolov8n.pt')

results = model(source="licensed-image.jpeg", show=True, conf=0.4, save=True)

# Extract bounding boxes, classes, names, and confidences
boxes = results[0].boxes.xyxy.tolist()
classes = results[0].boxes.cls.tolist()
names = results[0].names
confidences = results[0].boxes.conf.tolist()

# Iterate through the results
for box, cls, conf in zip(boxes, classes, confidences):
    print(box)
    print(cls)
    print(conf)